apiVersion: v1
kind: Service
metadata:
  name: postgres-service # Sets service name# Labels and Selectors
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port:  5432
    targetPort: 5432 # Sets port to run the postgres application
