apiVersion: v1
kind: Service
metadata:
  name: scrum-app # Sets service name
spec:
  # type: NodePort
  selector:
    app: scrum-back
  ports:
    - protocol: "TCP"
      port:  8080
      targetPort: 8080 # Sets port to run the postgres application

