apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: scrum-service
  name: scrum-service
spec:
  type: NodePort
  selector:
    app: scrum-ui
  ports:
   - protocol: TCP
     port: 4200
     targetPort: 80
